In [3]:
import numpy as np
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Data Simulation

In [39]:
n_samples = int(3.5e6)
np.random.seed(5000)
x = np.random.randint(6, 21, n_samples)
noise = np.random.normal(20000, 20000, n_samples)

In [40]:
x

array([17,  8,  7, ..., 19, 14, 18])

In [35]:
y = 4000 * x + noise - 10000

In [36]:
y.mean()

62006.555947344372

In [8]:
y

array([ 50253.72300087,  72636.05379379,  52329.98894255, ...,
        75199.50984292,  65559.40749933,  35806.50932666])

In [9]:
y.std()

26424.705290430076

# Finding an extreme seed 

In [12]:
import random

In [26]:
seed = 1
most_extreme_indices = []
lowest_mean = y.mean()
lowest_seed = 0

## Get the most extreme of 1000 samples. 
for _ in range(int(1e4)): ## Don't want the thing to run forever in case we never find it
    seed += 1
    indices = np.random.randint(0, len(y), 500)
    sample_mean = y[indices].mean()
    if sample_mean < lowest_mean: ## Only interested in negative means for this example
        lowest_mean = sample_mean
        most_extreme_indices = indices
        lowest_seed = seed
        
    
    

In [27]:
lowest_mean

57472.046128856418

In [28]:
most_extreme_indices

array([ 522332, 1338148, 3388576, 1548511,  989248, 3093262,  301683,
       2888422, 3137976, 3207624,  623249,  274506, 1768369,  935200,
       1299100,  576024, 1758882, 3146514, 2977921, 2379428, 1746601,
       1628902, 2738826,  576306, 3026497,  859422, 1500152,  971300,
       2776299, 2017572,  203883, 2575841, 1996333, 1614561, 1911797,
        523166,  722211,  286338, 1972203, 2522916, 2277031,  323554,
       3432827, 2851332, 1208545, 2569728, 1688599, 2292654,  175637,
        109772,  770601, 1988228,  859258, 1542751,  200502, 2902352,
        156066,  772730, 3215430, 2003121, 3109920, 2269504, 1072429,
       1521577, 2629222,  369470, 2793967, 3121802,  647002, 1630857,
        547579,  777268, 1492436, 3440582, 2467467,   37157,  820231,
       1563641,    4756, 1588375, 2867671, 2282545, 1490139, 1067376,
       1951816, 1866622, 2896122, 2302278, 2320647, 2296988, 1432613,
        423861,   68044, 2572170, 1161913, 1739828,  563236,  907465,
       2964326, 3499

In [29]:
lowest_seed

4375